---
title: 'Curso 2020/2021'
subtitle: 'Universitat de València - Universidad Católica de València'
author: 'Roberto Gil-Saura'
date: 'Última actualización en `r Sys.Date()`'
---

# Introducción

NOTA DEL AUTOR: 

> El presente texto fue redactado con el ánimo de realizar un análisis de situación de tema de trabajado seleccionado para este año. Los alumnos realizaron una búsqueda de fuentes bibliográficas y redactaron un documento similar a éste, cada uno con sus fuentes de información. El objetivo era realizar una aproximación personal al tema de trabajo y así poder ver de primera mano el estado de la situación, qué se estaba escribiendo, cómo, etc. . Para la mayoría de los alumnos este trabajo fue la primera vez que se aproximaban a una investigación de este tipo, un proyecto de investigación comercial o de mercados completo. 

En esta segunda ola, trataremos de profundizar en los aspectos que se hayan derivado del período acaecido entre actuaciones de investigación. Enfocaremos nuestro trabajo a realizar una valoración de las medidas que la Generalitat Valenciana ha venido tomando desde el inicio del nuevo año, y en especial desde la instauración de las nuevas medidas más restrictivas que en la actualidad (21 de enero de 2021) se presentan. Del mismo modo, variamos el enfoque de objetivos más a los efectos de la pandemia en las personas, nuevamente desde el punto de vista emocional, pero también en otros ámbitos del desarrollo personal.

## Briefing inicial

Nuestro cliente desea que profundicemos sobre las valoraciones de esas medidas, la creencia de su impacto positivo / negativo en la sociedad, ídem a nivel personal y la importancia que esa medida puede tener en el conjunto de la sociedad para atajar la evolución de la pandemia. Nótese que en el momento que se redacta este documento, la vacuna ya se encuentra disponible y es un motivo de esperanza para toda la sociedad en general. 

El objetivo general de esta investigación es comparar la situación antes de la tercera ola de la pandemia que situaremos después de las fiestas de la Navidad y derivada de las actuaciones de la sociedad entre las festividad de inicio de diciembre de 2020 y las festividades de inicio de 2021. Debemos buscar comprender al nuevo consumidor, para poder concluir acerca de la valoración de estos a instituciones, organizaciones en genéricas y como no  a las marcas, grandes beneficiadas o perjudicadas del momento pandémico.

De este modo, algunas de las cuestiones que suscitaron interés en la primera investigación deberían repetirse, a la par que se profundizará en nuevas valoraciones como por ejemplo el teletrabajo (si ha sido necesario) ha cambiado o está cambiando las relaciones trabajo - familia, la clasificación de la sociedad en función de su actitud hacia la pandemia y sus repercusiones, la mayor digitalización y por último, una valoración sobre las medidas que recientemente se han introducido, principalmente en la Comunitat Valenciana (sólo residentes).

